### PR TITLE
Native Vector Image Handling

### PR DESCRIPTION
**Pull request by KennyGoers**
Add app:buttonCompat attribute for specifying vector images for backward compatibility

### CODE REVIEW

**Comment by rcketscientist** [comment]
Do you have a reference for the change (ie: Android x source)?

**Comment by KennyGoers** [comment]
A reference for the source? As in a longer description of why? I just added
a new attribute and the support library call for loading any kind of
drawable.

**Comment by rcketscientist** [comment]
For the actual source change change I was wondering if you leveraged Google
source somewhere.  Mainly, I'm looking for their solution to this.  I
suspect the AppCompatResources is correct, but wanted to dig a little
deeper.

**Comment by KennyGoers** [comment]
That is the lowest level I've found for loading all manner of compatible
images in a backward compatible manner. No rocket science.

**Comment by rcketscientist** [comment]
lol, was looking to shortcut my research on the AppCompatResources and what the actual wiring was.  What's the deal with `buildToolsVersion` removal?

edit:
I was a little concerned about the backwards compatibility of AppCompatResources.  Didn't realize it was SDK side since there's ten other compat helpers and haven't been on the front end in quite a while.

**Comment by KennyGoers** [comment]
It's not required anymore each Target uses the latest from it's version
e.g. Target 26 uses build tools 26. It's help text from Android Studio to
remove it.

**Comment by rcketscientist** [comment]
Well, wasn't that a long overdue well-hidden update.

**Comment by rcketscientist** [comment]
Apparently the back-compat for vectors was buggy in a few versions, so this is soaking up far more time than I intended.

The `buttonCompat` irks me a bit, not your design, but that it's necessary.  I'll take a deeper look at this and will hopefully have this integrated tomorrow.

**Comment by KennyGoers** [comment]
Thanks,

If I could be overriden the base constructor or avoided it that would
avoided the problem, but the base throws that exception, I imagine it was
why Google added all the Compat properties to the support library
widgets...

I've been doing Android dev for over 6 years, nothing surprises me anymore

**Comment by rcketscientist** [comment]
lol, after the dumpster fire that was Storage Access Framework I set the Google bar so low you'd have trouble tripping over it.  

After searching for far too long I finally found `AppCompatImageView`:

https://github.com/aosp-mirror/platform_frameworks_support/blob/master/v7/appcompat/src/main/java/android/support/v7/widget/AppCompatImageView.java

IIRC I had to remove tinting due to some issues, the `AppCompatImageHelper`, might help with that.  Looks like their solution is exactly yours with tinting and some extra handling.

I'll have to see how good my memory is regarding the tinting issue and whether this would help.  I'll need the weekend to look this over.  Do you mind switching the PR to `development`?  I'll probably have some things to add before it gets to master.

**Comment by rcketscientist** [comment]
Never received an update on this PR.  Cleaning up, feel free to re-post to develop if still relevant.

**Pull request closed without merging**
